//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaloniaPrototype.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvaloniaPrototype.Resources.MainView", typeof(MainView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -aquifer-greeting-.
        /// </summary>
        public static string AquiferGreeting {
            get {
                return ResourceManager.GetString("AquiferGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -bible-well-greeting-.
        /// </summary>
        public static string BibleWellGreeting {
            get {
                return ResourceManager.GetString("BibleWellGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -loading-.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -load-internet-resource-.
        /// </summary>
        public static string LoadInternetResource {
            get {
                return ResourceManager.GetString("LoadInternetResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -load-local-resource-.
        /// </summary>
        public static string LoadLocalResource {
            get {
                return ResourceManager.GetString("LoadLocalResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -resource-content-.
        /// </summary>
        public static string ResourceContent {
            get {
                return ResourceManager.GetString("ResourceContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -resource-name-.
        /// </summary>
        public static string ResourceName {
            get {
                return ResourceManager.GetString("ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -save-local-resource-.
        /// </summary>
        public static string SaveLocalResource {
            get {
                return ResourceManager.GetString("SaveLocalResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -saving-.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
    }
}
